# Statistics

1 human =5.6 ft

1 coconut= 200ft

average/mean=102.8(Arithmetic mean)

Mean and it type:

    1>Arithmetic mean 

    2>Geometric mean

    3>Harmonic mean

In [1]:
# (92+92+92+92+92)/5  =average/arthmetic means

In [2]:
import math
(5.6*200*230*320)**(1/4)

95.28487295384882

In [3]:
(5.6+200+230+320)/4

188.9

In [4]:
import statistics as s

In [5]:
# restra =A
s.geometric_mean((3,80))

15.491933384829666

In [6]:
# restra =B
s.geometric_mean((4,70))

16.733200530681515

In [7]:
a=4
b=6

In [8]:
s.mean((a,b))    # arithmetic mean

5

In [9]:
s.geometric_mean((a,b))   # geometric mean

4.898979485566356

In [10]:
s.harmonic_mean((a,b))    #harmonic mean

4.8

# Median : center point of data

# Demo: 1 

creating a sample data then sorting it into ascending order or descending order

# Demo: 1.1: 

    Odd median :
        
        formula: Median=((n+1)/2)th   
        
        where:
        
            n=total number of values 
            
            th= term

In [11]:
x=[3,2,4,5,7,8,6,7,8]      # odd term median

In [12]:
x.sort()

In [13]:
x

[2, 3, 4, 5, 6, 7, 7, 8, 8]

# Demo:1.2:

    Even median
    
        formula: Median=((n/2)th+((n/2)+1)th)/2
        
        where,
            
            n=number of terms
            
            th= term

In [14]:
y=[0,1,2,3,4,5,6,7,8,9]
len(y)

10

In [15]:
z=[3,4,2,4,3,8,5,6,7,6]
z_tuple=(3,4,2,3,8,7,4,5,6,6)
# z.sort()
print("Sorted data in ascending order :",z)
print("length :",len(z))

Sorted data in ascending order : [3, 4, 2, 4, 3, 8, 5, 6, 7, 6]
length : 10


In [16]:
def myMedian(n):
    if type(n)==tuple:
        n=list(n)
        n.sort()
    else:
        n.sort()
    print((n[(len(n)//2)-1]+n[((len(n)//2)+1)-1])/2)

In [17]:
myMedian(z)
myMedian(z_tuple)

4.5
4.5


# Demo1.2.1:

even median and odd median calculation using statistics module of python 

In [18]:
z=[3,4,2,3,4,5,6,7,8,6]

In [19]:
s.median(z)

4.5

In [20]:
x=[3,2,4,5,7,8,6,7,8]   

In [21]:
s.median(x)

6

In [22]:
a=list((3,4,2,3,4,5,6,7,8,6))

In [23]:
a.sort()

In [24]:
a

[2, 3, 3, 4, 4, 5, 6, 6, 7, 8]

# Mode

help to get highest occurring value in the dataset

In [25]:
m=[2, 3, 3, 4, 4, 5, 6, 6, 7, 8]

In [26]:
s.mode(m)

3

In [27]:
s.multimode(m)

[3, 4, 6]

Mean:
    
    >Arithmetic mean
    
    > Geometric mean
    
    > Harmonic mean
    
Median:
    
    > odd term median
    
    > even term median
    
Mode:
    
    > single mode 
    
    > Multimode

Quantiles:
    
    > Q1
    
    > Q2
    
    > Q3
    
IQR(Inter Quartile Range):
    IQR=(Q3-Q1)

Max_Trend:

Min_Trend:
    
Structure data:

    > Pandas(Panel Datas)
    
Unstructured Data
    
    > Numpy 
    
Visualization:
    
    TUI:
        > Matplolib
        
        > Seaborn
    
    GUI:
        
        >Tableau
        
        >Power BI
        


# Date=5/12/2022
# Quantiles:

In [28]:
import statistics as s

In [29]:
x=[1,2,3,4,5,6,7,8]

In [30]:
s.quantiles(x)

[2.25, 4.5, 6.75]

In [31]:
y=[2,2,3,3.24,6,6.1,8,8.1]

In [32]:
q1,q2,q3=s.quantiles(y)

In [33]:
q1

2.25

In [34]:
q2

4.62

In [35]:
q3

7.525

In [36]:
IQR=q1-q3

In [37]:
print(IQR)

-5.275


In [38]:
IQR2=abs(q3-q1)
print(IQR2)

5.275


# what is Trend?

In [39]:
dataset=[100,100000,200000,300000,320000]

In [40]:
q1,q2,q3=s.quantiles(dataset)
s.quantiles(dataset)

[50050.0, 200000.0, 310000.0]

In [41]:
Max_trend=q3+1.5*IQR
Max_trend

309992.0875

In [42]:
Min_trend=q1-1.5*IQR
Min_trend

50057.9125

In [43]:
filter_dataset=[]
for i in dataset:
    if Max_trend>i and Min_trend<i:
        filter_dataset.append(i)
print(filter_dataset)
    

[100000, 200000, 300000]


In [44]:
filter_dataset=[]
for i in dataset:
    if Min_trend<i<Max_trend:
        filter_dataset.append(i)
print(filter_dataset)

[100000, 200000, 300000]


# Name of the tools, hold structure data.
database(sql database)

html table

xml

wml(semi-structured)

excel(semi-structured data)

ms access

etc...


# unstructured data

a datasets which has no level of it column called unstructured 

tools: numpy  (2005) (numpy built in c++)


Definition of Array:-> an Array contain similar type of values


In [45]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [46]:
import numpy as np

In [47]:
a=np.array([1,2,3,4,5,6,7,8,9,0])

In [48]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [49]:
print(a)

[1 2 3 4 5 6 7 8 9 0]


In [50]:
b=[1,2,3,4,5,6,7,8,9,0]
print(b)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 0]


In [51]:
c=[1,'krishna',1.2]
print(c)

[1, 'krishna', 1.2]


In [52]:
d=np.array([1,'krishna',1.2])
print(d)

['1' 'krishna' '1.2']


In [53]:
e=np.array([1,2,3,4,5,1.2])
print(e)

[1.  2.  3.  4.  5.  1.2]


In [54]:
f=np.array([1,2,3,4,5,1.2,"krishna"])
print(f)

['1' '2' '3' '4' '5' '1.2' 'krishna']


In [55]:
f=np.array([1,2,3,4,5,1.2,"1"])
print(f)

['1' '2' '3' '4' '5' '1.2' '1']


In [56]:
f=np.array([1,2,3,4,5,1.2,"1"],dtype=np.int8)
print(f)

[1 2 3 4 5 1 1]


In [57]:
bin(10)

'0b1010'

In [58]:
64+32+16+8+4+2+1

127

In [59]:
f=np.array([1,2,3,4,5,6])
min(f)

1

In [60]:
f=np.array([1,2,3,4,5,1.2,"10.0"],dtype=np.float16)
print(f)
g=np.array(f,dtype=np.int16)
print(g)

[ 1.   2.   3.   4.   5.   1.2 10. ]
[ 1  2  3  4  5  1 10]


In [61]:
a="10.0"
int(a)

ValueError: invalid literal for int() with base 10: '10.0'

In [62]:
h=np.array([1,2,3,4,5,6],dtype=np.str_)
print(h)

['1' '2' '3' '4' '5' '6']


# There are three type of array

1 > scaler   # a value which has 0 dimension

2 > vector

3 > matrix

In [63]:
i=np.array(100)
print(i)
i.ndim           # scaler array which has no dimension or 0 dimension

100


0

In [64]:
j=np.array([100,111,2,3,4,5,5,6,])    # 1 dimensional array of vector 
print(j)
j.ndim

[100 111   2   3   4   5   5   6]


1

In [65]:
k=np.array([[1,2],[2,3]])     #2 Dimensional array called matrix
print(k)
k.ndim

[[1 2]
 [2 3]]


2

In [66]:
l=np.array([[[100]]])
print(l)
l.ndim

[[[100]]]


3

In [67]:
l=np.array([[[1,2],[2,3]],[[4,3],[8,9]]])   # 3 dimensional array
print(l)
l.ndim

[[[1 2]
  [2 3]]

 [[4 3]
  [8 9]]]


3

In [68]:
toy=np.array(['video game','trum card','contra', 'computer'])

In [69]:
toy

array(['video game', 'trum card', 'contra', 'computer'], dtype='<U10')

In [70]:
marks=np.array([[1,'A',75,50,70],[2,'B',33,40,80],[3,'C',90,100,91]])

In [71]:
marks

array([['1', 'A', '75', '50', '70'],
       ['2', 'B', '33', '40', '80'],
       ['3', 'C', '90', '100', '91']], dtype='<U11')

In [72]:
import cv2

# Application of array: 

0D: 27

1D: to create list

2D: to store tabuler data

3D: 3D array is used to store image

4D: to store video.

In [73]:
demo1=np.array([i for i in range(100)])    # this is an array
print(demo1)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [74]:
demo2=[i for i in range(100)]      # this a list
print(demo2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


# Array is faster then list 

In [75]:
import sys

In [76]:
sys.getsizeof(demo1)

504

In [77]:
sys.getsizeof(demo2)

920

In [78]:
import random

In [79]:
random.randint(1,10)

4

In [80]:
np.random.randint(1,10,(3,3,2))  # start, end, size of array

array([[[7, 2],
        [6, 6],
        [3, 3]],

       [[4, 1],
        [9, 6],
        [5, 7]],

       [[6, 3],
        [7, 1],
        [4, 3]]])

In [81]:
np.random.uniform(0,10,10)  # float value

array([7.62115851, 2.77159899, 6.39887706, 2.31009594, 5.44669691,
       1.26826975, 3.40079606, 9.10873385, 1.71638708, 6.41535536])

In [82]:
np.random.randint(1,10,(3,2),dtype=np.int16)   # intial_value, end_value(exclusive), size(3,2)          #integer values

array([[2, 7],
       [1, 6],
       [3, 1]], dtype=int16)

In [83]:
x=np.random.randint(1,10,(3,2))

In [84]:
x

array([[8, 4],
       [8, 5],
       [6, 8]])

In [85]:
np.array(x,dtype=np.float16)

array([[8., 4.],
       [8., 5.],
       [6., 8.]], dtype=float16)

In [86]:
np.linspace(1,11,21,dtype=np.int16)   # uniformly equidistance data create using linspace between two point start and end both head are inclusive

array([ 1,  1,  2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7,  8,  8,  9,
        9, 10, 10, 11], dtype=int16)

In [87]:
range(10)

range(0, 10)

In [88]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
X=np.random.randint(1,10,(3,2))

In [90]:
X

array([[2, 5],
       [2, 6],
       [4, 6]])

In [91]:
y=X.flatten()
y

array([2, 5, 2, 6, 4, 6])

In [92]:
X.resize((2,3))    # do permanent changes in existing array

In [93]:
X

array([[2, 5, 2],
       [6, 4, 6]])

In [94]:
X

array([[2, 5, 2],
       [6, 4, 6]])

In [95]:
z=np.random.randint(1,10,(3,2))

In [96]:
z

array([[9, 2],
       [4, 5],
       [4, 6]])

In [97]:
z.flatten()

array([9, 2, 4, 5, 4, 6])

In [98]:
z.reshape((2,3))   # not do permanent changes into array

array([[9, 2, 4],
       [5, 4, 6]])

In [99]:
z.reshape((2,3),order='F')

array([[9, 4, 5],
       [4, 2, 6]])

In [100]:
z

array([[9, 2],
       [4, 5],
       [4, 6]])

In [101]:
array1=np.arange(16)

In [102]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [103]:
array1.reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [104]:
array1.reshape((3,2))

ValueError: cannot reshape array of size 16 into shape (3,2)

In [105]:
array1.reshape(2,-1)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [106]:
array1.reshape((-1,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [107]:
array1.reshape((-1,2),order='F')

array([[ 0,  8],
       [ 1,  9],
       [ 2, 10],
       [ 3, 11],
       [ 4, 12],
       [ 5, 13],
       [ 6, 14],
       [ 7, 15]])

In [108]:
array1.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [113]:
one=np.array([1])

In [114]:
one.reshape(-1,-1)

ValueError: can only specify one unknown dimension

In [115]:
len(array1)

16

In [116]:
len((array1.reshape(2,8)).flatten())

16

In [117]:
a=array1.reshape(2,8)

In [118]:
b=a.flatten()

In [119]:
len(b)

16

In [120]:
a=np.arange(16)

In [121]:
a=a.flatten()
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [122]:
a.resize(3,4,refcheck=False)

In [123]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

# Broadcasting

In [124]:
list1=[1,2,3,4,5]
list2=[3,4,5,6,7]

In [125]:
# list broadcasting using for loop rule1:
empty=[]
for i,j in zip(list1,list2):
    empty.append(i+j)

In [126]:
empty

[4, 6, 8, 10, 12]

In [127]:
# list broadcasting using for loop rule2:
empty2=[i+j for i,j in zip(list1,list2)]
empty2

[4, 6, 8, 10, 12]

In [128]:
list1+list2

[1, 2, 3, 4, 5, 3, 4, 5, 6, 7]

In [129]:
array1=np.array([1,2,3,4,5])
array2=np.array([2,3,4,5,6])

In [130]:
array1+array2

array([ 3,  5,  7,  9, 11])

In [131]:
np.concatenate((array1,array2))

array([1, 2, 3, 4, 5, 2, 3, 4, 5, 6])

In [132]:
array1*array2

array([ 2,  6, 12, 20, 30])

In [133]:
array1/array2

array([0.5       , 0.66666667, 0.75      , 0.8       , 0.83333333])

In [134]:
np.round(array1/array2,decimals=2)

array([0.5 , 0.67, 0.75, 0.8 , 0.83])

In [135]:
a=np.random.uniform(1,10,10)

In [136]:
np.round(a,2)

array([8.73, 8.69, 2.02, 2.01, 4.03, 4.79, 5.15, 2.65, 8.28, 8.92])

array_name.reshape(()) #    no need of permanent change in array_name 

array_name.resize()  # when we need permament change in array_name

In [137]:
array_name=np.array([1,2,3,4,5,6,7,8,9,0])
array_name

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [138]:
array_name.reshape((2,5),order='C')

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [139]:
array_name

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [140]:
array_name.reshape((2,5),order='F')

array([[1, 3, 5, 7, 9],
       [2, 4, 6, 8, 0]])

In [141]:
array_name

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [142]:
array_name.resize((2,5))   # it change our base array array_name

In [143]:
array_name

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [144]:
array_name.resize((5,2))

In [145]:
array_name

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [9, 0]])

In [146]:
array_name.resize((4,2),refcheck=False)

In [147]:
array_name

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [148]:
array_name.resize((6,2),refcheck=False)

In [149]:
array_name

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [0, 0],
       [0, 0]])

In [150]:
array_name

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8],
       [0, 0],
       [0, 0]])

# vstack and hstack

In [151]:
a=np.random.randint(1,10,(3,2))   # 2d array

In [152]:
a

array([[6, 2],
       [1, 3],
       [4, 6]])

In [153]:
b=np.random.randint(1,10,(2,2))  # 2D array

In [154]:
b

array([[1, 6],
       [6, 8]])

In [155]:
np.vstack((a,b))    # 2D array

array([[6, 2],
       [1, 3],
       [4, 6],
       [1, 6],
       [6, 8]])

# 3D array stacking

In [156]:
c=np.random.randint(1,10,(3,2,2))
c

array([[[8, 5],
        [9, 4]],

       [[9, 8],
        [4, 1]],

       [[1, 7],
        [2, 3]]])

In [157]:
d=np.random.randint(1,10,(4,2,2))
d

array([[[8, 7],
        [4, 5]],

       [[5, 6],
        [1, 6]],

       [[7, 2],
        [9, 9]],

       [[8, 1],
        [9, 9]]])

In [158]:
np.vstack((c,d))

array([[[8, 5],
        [9, 4]],

       [[9, 8],
        [4, 1]],

       [[1, 7],
        [2, 3]],

       [[8, 7],
        [4, 5]],

       [[5, 6],
        [1, 6]],

       [[7, 2],
        [9, 9]],

       [[8, 1],
        [9, 9]]])

# hstack

In [159]:
e=np.random.randint(1,10,(2,3))
e

array([[3, 3, 2],
       [9, 1, 2]])

In [160]:
f=np.random.randint(1,10,(2,10))
f

array([[1, 8, 6, 5, 1, 4, 1, 6, 9, 3],
       [5, 3, 1, 6, 1, 1, 9, 5, 6, 8]])

In [161]:
np.hstack((e,f))

array([[3, 3, 2, 1, 8, 6, 5, 1, 4, 1, 6, 9, 3],
       [9, 1, 2, 5, 3, 1, 6, 1, 1, 9, 5, 6, 8]])

# hstacking with 3D array

In [162]:
g=np.random.randint(1,10,(3,2,2))
g

array([[[3, 6],
        [5, 3]],

       [[3, 1],
        [9, 1]],

       [[6, 5],
        [7, 2]]])

In [163]:
h=np.random.randint(1,10,(5,2,2))
h

array([[[1, 5],
        [9, 6]],

       [[5, 8],
        [8, 3]],

       [[4, 5],
        [7, 1]],

       [[5, 5],
        [7, 1]],

       [[3, 8],
        [4, 1]]])

In [164]:
np.vstack((g,h))

array([[[3, 6],
        [5, 3]],

       [[3, 1],
        [9, 1]],

       [[6, 5],
        [7, 2]],

       [[1, 5],
        [9, 6]],

       [[5, 8],
        [8, 3]],

       [[4, 5],
        [7, 1]],

       [[5, 5],
        [7, 1]],

       [[3, 8],
        [4, 1]]])

In [165]:
i=np.random.randint(1,10,10)
i

array([6, 6, 5, 6, 2, 1, 1, 4, 3, 1])

In [166]:
np.min(i)

1

In [167]:
np.max(i)

6

In [168]:
np.sum(i)

35

In [169]:
np.mean(i)

3.5

In [170]:
np.std(i)

2.0615528128088303

In [171]:
j=np.array([[1,2,3,4,5],[6,7,8,9,0]])
j

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [172]:
np.min(j)

0

In [173]:
np.max(j)

9

In [174]:
np.mean(j)

4.5

In [175]:
np.std(j)

2.8722813232690143

In [176]:
np.argmin(j)

9

In [177]:
j.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [178]:
j

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [179]:
np.argmax(j,axis=1) #it detect larger value's index row-wise

array([4, 3], dtype=int64)

In [180]:
np.argmax(j,axis=0)

array([1, 1, 1, 1, 0], dtype=int64)

In [181]:
j

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [182]:
np.sum(j)

45

In [183]:
print("sum of all value in array:",np.sum(j))
print("sum of all values according to row in array :",np.sum(j,axis=1))

sum of all value in array: 45
sum of all values according to row in array : [15 30]


In [184]:
print("Sum of all values in array :",np.sum(j))
print("Sum of all values in array according to column wise :",np.sum(j,axis=0))

Sum of all values in array : 45
Sum of all values in array according to column wise : [ 7  9 11 13  5]


# argmax and argmin

In [185]:
a=[3,4,5,2,5,4,7,4,2]

In [186]:
max(a)

7

In [212]:
def new(arg):  # [67, 46, 86, 24, 56, 52, 48, 46, 83, 38]  #1234
    counter=-1
    drg=arg.copy()   #[67, 46, 86, 24, 56, 52, 48, 46, 83, 38]  #2345
    drg.sort()      #[24, 38, 46, 46, 48, 52, 56, 67, 83, 86]  # 2345
    d=drg[-1]   #86
    for i in arg:   #[67, 46, 86, 24, 56, 52, 48, 46, 83, 38]  #1234
        counter+=1
        if i==d:     #i=86 d=86   # i==d  True
           break
    return counter

In [204]:
new(a)

[2, 2, 3, 4, 4, 4, 5, 5, 7]


8

In [213]:
d=np.random.randint(1,100,10)
d

array([67, 46, 86, 24, 56, 52, 48, 46, 83, 38])

In [214]:
new(d)

2

In [215]:
d.sort()

In [218]:
d=[67, 46, 86, 24, 56, 52, 48, 46, 83, 38]

In [219]:
np.argmax(d)

2

In [220]:
np.argmin(d)

3

In [221]:
def old(arg):  # [67, 46, 86, 24, 56, 52, 48, 46, 83, 38]  #1234
    counter=-1
    drg=arg.copy()   #[67, 46, 86, 24, 56, 52, 48, 46, 83, 38]  #2345
    drg.sort()      #[24, 38, 46, 46, 48, 52, 56, 67, 83, 86]  # 2345
    d=drg[0]   #86
    for i in arg:   #[67, 46, 86, 24, 56, 52, 48, 46, 83, 38]  #1234
        counter+=1
        if i==d:     #i=86 d=86   # i==d  True
           break
    return counter

In [222]:
old(d)

3

In [223]:
d

[67, 46, 86, 24, 56, 52, 48, 46, 83, 38]

In [226]:
e=np.reshape(d,(5,2))
e

array([[67, 46],
       [86, 24],
       [56, 52],
       [48, 46],
       [83, 38]])

In [227]:
np.argmin(e)

3

In [228]:
np.argmax(e)

2

In [229]:
old(e)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [237]:
def old(arg):  # [67, 46, 86, 24, 56, 52, 48, 46, 83, 38]  #1234
    counter=-1
    drg=arg.copy()   #[67, 46, 86, 24, 56, 52, 48, 46, 83, 38]  #2345
    a=arg.ndim
    if a<2:
        pass
    else:
        drg=drg.flatten()
        arg=arg.flatten()
    drg.sort()      #[24, 38, 46, 46, 48, 52, 56, 67, 83, 86]  # 2345
    d=drg[0]   #86
    for i in arg:   #[67, 46, 86, 24, 56, 52, 48, 46, 83, 38]  #1234
        counter+=1
        if i==d:     #i=86 d=86   # i==d  True
           break
    return counter

In [231]:
a=np.array([[2,3],[3,5]])

In [232]:
a.sort()

In [234]:
a.flatten()

array([2, 3, 3, 5])

In [238]:
old(a)

0

In [243]:
a=np.random.randint(1,10,8)
a

array([4, 1, 8, 5, 4, 2, 3, 4])

In [248]:
b=np.reshape(a,(1,2,4))
b

array([[[4, 1, 8, 5],
        [4, 2, 3, 4]]])

In [249]:
b[0][0]

array([4, 1, 8, 5])

In [250]:
b[0][0][0]

4

In [251]:
old(b)

1

In [255]:
np.argmin(b,axis=0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int64)

In [256]:
b=np.reshape(a,(2,4))
b

array([[4, 1, 8, 5],
       [4, 2, 3, 4]])

In [257]:
np.argmin(b,axis=1)

array([1, 1], dtype=int64)

In [258]:
np.argmin(b,axis=0)

array([0, 0, 1, 1], dtype=int64)

# sorting

In [267]:
a=np.random.randint(1,10,10)
a

array([6, 9, 7, 9, 2, 4, 9, 6, 9, 8])

In [261]:
a.sort()

In [262]:
a

array([1, 2, 3, 4, 4, 5, 5, 6, 8, 9])

In [268]:
b=np.resize(a,(5,2))
b

array([[6, 9],
       [7, 9],
       [2, 4],
       [9, 6],
       [9, 8]])

In [269]:
b.sort()

In [271]:
b.sort(axis=0)

In [272]:
b

array([[2, 4],
       [6, 9],
       [6, 9],
       [7, 9],
       [8, 9]])

In [275]:
c=b.flatten()
c

array([2, 4, 6, 9, 6, 9, 7, 9, 8, 9])

In [276]:
np.square(c)

array([ 4, 16, 36, 81, 36, 81, 49, 81, 64, 81], dtype=int32)

In [279]:
f=np.sqrt(c)
f

array([1.41421356, 2.        , 2.44948974, 3.        , 2.44948974,
       3.        , 2.64575131, 3.        , 2.82842712, 3.        ])

In [281]:
g=np.round(f,decimals=2)
g

array([1.41, 2.  , 2.45, 3.  , 2.45, 3.  , 2.65, 3.  , 2.83, 3.  ])

In [283]:
np.array(g,dtype=np.int16)

array([1, 2, 2, 3, 2, 3, 2, 3, 2, 3], dtype=int16)

In [1]:
import numpy as np

In [2]:
np.tan(90)

-1.995200412208242

In [8]:
a=np.array([i for i in range(10)])
print(a)
np.log(a)

[0 1 2 3 4 5 6 7 8 9]


C:\Users\Ducat\AppData\Local\Temp\ipykernel_6712\1553383633.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(a)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [5]:
b=np.array(np.arange(10))

In [6]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.tan(b)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566])

In [10]:
np.log10(b)

C:\Users\Ducat\AppData\Local\Temp\ipykernel_6712\3416214235.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(b)


array([      -inf, 0.        , 0.30103   , 0.47712125, 0.60205999,
       0.69897   , 0.77815125, 0.84509804, 0.90308999, 0.95424251])

In [11]:
np.cos(b)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [14]:
np.arange(1,7)
np.resize(np.arange(1,7),(2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
a=np.arange(1,7)
b=np.resize(a,(2,3))
b

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
np.transpose(b)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [23]:
b.sum()

21

In [24]:
np.sum(b)

21

In [25]:
b.min()

1

In [26]:
np.min(b)

1

in matrix dot product 

suppose we have two matrix of size (2(r1),2(c1)) and  (2(r2),3(c2))

what we check to evalute dot product of two matrix:

    rule 1: c1==r2 # multiplication is possible
    rule 2: dimension of all the array must be same example if matrix a is 2d then matrix b must be 2d then we apply rule 1

    size of matrix after dot product: r1xc2



In [28]:
a=np.array([[1,2],[3,4]])   # size of array a =(2x2)
a

array([[1, 2],
       [3, 4]])

In [29]:
b=np.array([[2,3,4],[1,2,3]])
b

array([[2, 3, 4],
       [1, 2, 3]])

In [30]:
a.dot(b)

array([[ 4,  7, 10],
       [10, 17, 24]])

In [31]:
1a=10

SyntaxError: invalid syntax (3782790406.py, line 1)

In [32]:
@a=10

SyntaxError: invalid syntax (1563080312.py, line 1)

In [33]:
a@b

array([[ 4,  7, 10],
       [10, 17, 24]])

In [34]:
np.dot(a,b)

array([[ 4,  7, 10],
       [10, 17, 24]])